### PR TITLE
Describe operations and workflow

### PR DESCRIPTION
**Pull request by dkoslicki**
This is a work in progress, more commits will be made in this branch subsequently

### CODE REVIEW

**Comment by RichardBruskiewich** [comment]
Hi @dkoslicki, how is your work on PR https://github.com/NCATSTranslator/translator-developer-documentation/pull/5 going? Are you almost ready to convert it from draft into a reviewable PR? Maybe if the PR is in good enough shape as an initial draft, we can merge it then iterate further later? I fully trust that your authorship has already resulted in a decent first pass.

**Comment by dkoslicki** [comment]
Hi @RichardBruskiewich , I think this is ok as a first draft, so submitting it for review now

**Comment by RichardBruskiewich** [comment]
> Hi @RichardBruskiewich , I think this is ok as a first draft, so submitting it for review now

Thanks! I'll take a look!

**Review by RichardBruskiewich — APPROVED** [review]
Looks great!

**Pull request merged**
